### ISSUE TITLE
Rolling code replay

### ISSUE THREAD

**Issue by XxSwiftflamexX** [cclabsInc/RFCrack#10]
I managed to jam signals using rpitx on a raspberry pi while simultaneously capturing signals using a yard stick one with the live replay option. I believe I managed to not capture any of the jamming signals and only the ones I actually wanted, but when I replay them nothing happens. What could be the issue?

**Comment by cclabsInc** [comment]
It might have goten through and your jamming didn't work.. so the rolling code protection is working and your distance, or signal strength or another issue may be in play.  Adjust your settings and location.
