### ISSUE TITLE
'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by SorenAndreasen** [cclabsInc/RFCrack#11]
I have 2 YS1's inserted and I believe I have all necessary libraries and drivers, but when I call 
sudo python RFCrack.py -r -M MOD_ASK_OOK -F 433900000
it gives me this error everytime, just the exact byte that it's confused about is changing all the time

**Comment by cclabsInc** [comment]
Hmmm I dont have a yardstick on me while on travel.. but I will check that request when I get home next week.. . Have you tried this from another machine?  Wonder if something is going on locally.

**Comment by serolee** [comment]
hello I've also got the same problem.
I have 2 YS1 and I've trued the following:
- running 'python RFCrack.py -r -M MOD_2FSK -F 315000000'
however that didn't work so I tried

- then running the same examples from README:
   Rolling Code:        python RFCrack.py -r -M MOD_2FSK -F 314350000
    Adjust RSSI Values:  python RFCrack.py -r -M MOD_2FSK -F 314350000 -U -100 -L -10

and I get the same error

Traceback (most recent call last):
  File "RFCrack.py", line 184, in <module>
    attacks.rollingCode(d, rf_settings, args.rolling_code, args.jamming_variance)
  File "/root/Apps/rfcat/RFCrack/src/attacks.py", line 15, in rollingCode
    roll_captures, signal_strength = tools.capturePayload(d, rolling_code, rf_settings)
  File "/root/Apps/rfcat/RFCrack/src/RFFunctions.py", line 21, in capturePayload
    signal_strength= 0 - ord(str(d.getRSSI()))
  File "/usr/lib/python2.7/dist-packages/future/types/newstr.py", line 102, in __new__
    return super(newstr, cls).__new__(cls, value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 0: ordinal not in range(128)


Have I done something wrong.
My RFCrack repo is inside my rfcat does that affect this?
Or is there something else.

**Comment by serolee** [comment]
Here is another attempt:

root:~/Apps/rfcat/RFCrack# python RFCrack.py -r -M MOD_2FSK
Don't forget to change the default frequency and modulation type
ROLLING CODE REQUIRES 2 YardSticks Plugged In
Starting Jamming on: 315080000
SIGNAL STRENGTH: -15
RF CAPTURE: 
e07dffeffad2f98c77a69860416067a810050978045df85810000889bbcc6160240007677e4460440095bf42800060c02edc050201801d7cbe0040040022b96e2554808a8e8ac4000580923daee90006280d25f6830d241484d4edc00020040002c7a000001000086c20900009880c6c18004839000efba0405028000db32860204312008a42b197c729614180f50569079c5231d05f329b7cfc52f02e2f7a73631b7379aa5b6b1f2937ad415e9ee2cee5b7ebf5fffefbeabb5d0c129f3f6b2efca3eef6d8e25d5dca24afdceffba6671eb53dffbbe9eedddbdaa1f9d7a3b8af19dd6e2ac3e7f1a2ba964f4f7dc07e53d8dbd8e5e8ffee9baff6

Traceback (most recent call last):
  File "RFCrack.py", line 184, in <module>
    attacks.rollingCode(d, rf_settings, args.rolling_code, args.jamming_variance)
  File "/root/Apps/rfcat/RFCrack/src/attacks.py", line 15, in rollingCode
    roll_captures, signal_strength = tools.capturePayload(d, rolling_code, rf_settings)
  File "/root/Apps/rfcat/RFCrack/src/RFFunctions.py", line 21, in capturePayload
    signal_strength= 0 - ord(str(d.getRSSI()))
  File "/usr/lib/python2.7/dist-packages/future/types/newstr.py", line 102, in __new__
    return super(newstr, cls).__new__(cls, value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 0: ordinal not in range(128)


You can see it captured one signal and then stopped.
I also notice when I'm running rolling code capture (-r without -M or -F) the attack immediately records a keyfob click all the time. Is it normal that doing captures inside city skyscrapers, that I will constantly be picking up keyfob presses or something emulating this around me. I've tried it in two locations and it seems I can't target the rolling code target in my living room I want to target. 

I can capture results using the live signal sniffer for the specific 315000000 signal. No problem. however I can't have the rolling code capture run long enough before it captures other signals.
Is this where picking specific -U and -L upper and lower RSSI values come in?
And if so, how can I find out what my target keyfob's RSSI value is?
I have the target keyfob.
I have URH and GNUradio, can they help me idetify what RSSI value I need.

**Comment by serolee** [comment]
Hi clans to answer your question you’ve asked Soren, I’ve actually installed all the denpendencies and rfcat, and RFCrack on 3 different systems: one kali nethunter device, another kali system running on vmware and a laptop with the kali distro. 

They all have the same problem when running -r -M MOD_2FSK
The result is the same:
UnicodeDecodeError: 'ascii' codec can't decode byte 0x[“insert digits”] in position 0: ordinal not in range(128)

Is this something you’ve come across cclabs? If not can you help identify what repository or dependency we are missing. I tried for the past week and I’ve got no clues. 
Thanks in advance.

**Comment by scorpionul222** [comment]
uses parrot os 4.6 without installing other libraries already contains rfcat

**Comment by cclabsInc** [comment]
I an try to take a look.. could be updates to some library that breaks something.. I have not done much RF in the last year.. last I checked things worked well in Kali with the Pre-Reqs installed.. I will take a look this weekend and make sure things are working on newest builds of OSX and Linux.. 
However note that Python2 is depreciating soon and when the new library is rleased for rfcat so I will be recoding this for python3 at this time as well..

**Comment by ThouChosenOne** [comment]
I also get a similar error at the end with RFCrack when trying to run the replay attack via:
sudo python RFCrack.py -i -F 315000000.
tacks.replayLiveCapture(d, args.rolling_code, rf_settings)
  File "/home/ty/RFCrack/src/attacks.py", line 44, in replayLiveCapture
    replay_capture, signal_strength = tools.capturePayload(d,rolling_code, rf_settings)
  File "/home/ty/RFCrack/src/RFFunctions.py", line 21, in capturePayload
    signal_strength= 0 - ord(str(d.getRSSI()))
  File "/home/ty/.local/lib/python2.7/site-packages/future/types/newstr.py", line 102, in __new__
    return super(newstr, cls).__new__(cls, value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd4 in position 0: ordinal not in range(128)

**Comment by coulie87** [comment]
I got the same error message

File "RFCrack.py", line 201, in <module>
    attacks.replayLiveCapture(d, args.rolling_code, rf_settings)
  File "/home/RFCrack/src/attacks.py", line 44, in replayLiveCapture
    replay_capture, signal_strength = tools.capturePayload(d,rolling_code, rf_settings)
  File "/home/RFCrack/src/RFFunctions.py", line 21, in capturePayload
    signal_strength= 0 - ord(str(d.getRSSI()))
  File "/home/.local/lib/python2.7/site-packages/future/types/newstr.py", line 104, in __new__
    return super(newstr, cls).__new__(cls, value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdd in position 0: ordinal not in range(128)

Is there already a fix available? 

Thank you!

**Comment by cclabsInc** [comment]
I have not run into any issues myself. It may be updates to new libraries or just the specific request you captured is runing into issues.  Is this giving you a issue on everyhing you do or one specific scenario? 
On a side note RFCat libraries are going to be replaced with a python3 version soon as python2 is depreciated soon.  RFCrack will be updated that time to use new libraries with python3

**Comment by ThouChosenOne** [comment]
I was able to fix my error by making sure I was as close to the actual frequency as possible.
Example: For my car keyfob 314313000 seemed to do the trick, as opposed to just 314000000. You can also try being closer to the yardstick one when activating the signal.
@coulie87 Let me know if that fixes your problem.

May have something to do with the code for the command as python RFCrack.py -k -f (freq) seems to work well for me all the time.
Either way I don't know, I am just guessing based off my experience playing around with this the last couple of weeks.
@cclabsInc I really appreciate your work and look forward to actually learning how all these commands work instead of just typing them in. Thank You!

**Comment by coulie87** [comment]
@cclablnc, @ThouChosenOne; I managed to fix the error by changing the ord(str(d.getRSSI())) command to ord(d.getRSSI) in line 21 in RFFunctions.py. Although I don't get an error anymore, I'm not able to play the replay attack as my replayed frequency seems to be shifted compared to the original.

**Comment by cclabsInc** [comment]
As thouChosenOne stated above.. this is probably an issue with your frequency and distance, you need to adjust your testing environment.  Not an issue with the code.  RF is a bit weird to deal with sometimes when there is interference..   If you start changing the variable format its going to break a lot of things as that needs to be in a string format for processing.

**Comment by cclabsInc** [comment]
Not a coding issue... user issue with frequency and distance.
