### ISSUE TITLE
When will RFCrack libraries be updated to work with python3?

### ISSUE THREAD

**Issue by serolee** [cclabsInc/RFCrack#12]
Hello cclabs, appreciate the hard work,
I was wondering as its Jan 2020, and python 2 is depreciated, do we need to do anything to make RFCrack work with python 3, or will we have to wait for you to make the next iteration and update.

Many thanks from the community.

**Comment by cclabsInc** [comment]
I will update this to Python3 and add on to its functionality when the RFCat libraries are ported to python3.  Those library dependencies are currently python2 though I have seen notes online they will be ported over. At that time I will for sure update this software for my needs and share it.

**Comment by cclabsInc** [comment]
I just left a comment on that project to inquire about a future python3 library.

**Comment by serolee** [comment]
I notice this thread a while back talking about porting rfcat to python3,
is this port sufficient for you to create a python3 compatible RFCrack?
Here: https://github.com/nosajthenitram/rfcat/tree/python3_port

Here is the original thread: https://bitbucket.org/atlas0fd00m/rfcat/issues/17/python-3-support

**Comment by CourseAccess** [comment]
When the port is completed and in the official github I will update to python3.. As of right now I don't believe it is completed and its not in the official release.

**Comment by serolee** [comment]
Hi Ollie, fantastic I can't wait for you to update this to Python3. 

In the meantime I've found a temporary workaround to avoid many of the archived 'Issues' in this repo based on the underlying Python2.7 foundation. By using an earlier dated rfcat repo from November 5th 2018, 
(https://github.com/atlas0fd00m/rfcat/tree/4a446c8b527f178eeaef8670c306cda320890347)

and the current version of RFCrack, many of the 'ASCII" related problems aren't apparent. 
These problems mainly happen on Nethunter for android, Kali linux on desktop and even on Mac OS (brew).

Again, I look forward to seeing this updated along with rfcat and python3, please let me know where I can motivate you and contribute a donation :)

**Comment by cclabsInc** [comment]
Thanks for posting the version info that your testing has it working with ! 

Yea for sure this is not coded for use on your android and there will be no android support at any time.. This was coded for OSX and also seems to work just fine on linux during my initial testing but I was doing my research from OSX. 

Moving forward with Python3 I will be doing all of the coding / R&D for Linux based distros as I have moved off of the OSX platform. 

If you do happen to see a python3 update for RFCat let me know and I will fully update that asap along with adding new features.. But at this point I am waiting for Python3 support before spinning wheels coding something that may not work later on.

**Comment by cclabsInc** [comment]
Updated my install notes with your link
