### ISSUE TITLE
Live Signal Identification and Comparison (Use 2 Console Windows)

### ISSUE THREAD

**Issue by ners11** [cclabsInc/RFCrack#14]
Hi! I need Your help.
I have this error:

root@nrs:~/rfcat/RFCrack# python RFCrack.py -c -u 3f87f1c03f8701fc380fe1c0380e01c07f0e03f87f0e03c0701e0380fe1c0780e -n
----------Start Signals In Press--------------
Percent Chance of Match for press is: 0.02
Percent Chance of Match for press is: 0.12
Percent Chance of Match for press is: 0.02
Percent Chance of Match for press is: 0.07
Percent Chance of Match for press is: 0.16
Percent Chance of Match for press is: 0.07
----------End Signals In Press------------
Traceback (most recent call last):
  File "RFCrack.py", line 219, in <module>
    utilities.logTail(my_clicker)
  File "/root/rfcat/RFCrack/src/utilities.py", line 29, in logTail
    percent = my_clicker.liveClicks()                                      
  File "/root/rfcat/RFCrack/src/Clicker.py", line 57, in liveClicks        
    self.openImage('./imageOutput/LiveComparison.png')                     
  File "/root/rfcat/RFCrack/src/Clicker.py", line 124, in openImage        
    subprocess.call([imageViewerFromCommandLine, path])                    
  File "/usr/lib/python2.7/subprocess.py", line 172, in call               
    return Popen(*popenargs, **kwargs).wait()                              
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__           
    errread, errwrite)                                                     
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child    
    raise child_exception                                                  
OSError: [Errno 2] No such file or directory

**Comment by serolee** [comment]
Hey, if you're not using the rfcat repo from November 5th 2018, make sure you do.
(https://github.com/atlas0fd00m/rfcat/tree/4a446c8b527f178eeaef8670c306cda320890347)

If that doesn't solve the problem, then it appears theres no fix until rfcat is ported to python3, and cclabs updates RFCrack to comply with python3.

**Comment by cclabsInc** [comment]
Need to use Nov 5th 2018 repo of rfcat untill they release a Python3 version and then I will update the code to python3
