### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by flexonax** [cclabsInc/RFCrack#17]
all day automatic save rolling codes?

1-start jamming 
2-start sniffing 
3-saving /save/file1

waiting 1mnt.....

1-start jamming 
2-start sniffing 
3-saving /save/file2

waiting 1mnt......

**Comment by cclabsInc** [comment]
No new features are being added to this project until the python3 version of the needed libraries are released at which point I will re-code it and maintain it.

**Comment by cclabsInc** [comment]
> all day automatic save rolling codes?
> 
> 1-start jamming
> 2-start sniffing
> 3-saving /save/file1
> 
> waiting 1mnt.....
> 
> 1-start jamming
> 2-start sniffing
> 3-saving /save/file2
> 
> waiting 1mnt......

OK so I am updating this project to Python3 now.. what exactly are you asking for?

**Comment by cclabsInc** [comment]
Never got a response.. Closing.. Re-open if you feel like expanding on that request..
