### ISSUE TITLE
jamming multiple frequency using USRP B210 dual channel?

### ISSUE THREAD

**Issue by AL-Muslim** [cclabsInc/RFCrack#19]
is it possible to jam on multiple frequencies using USRP b210 2x2 MIMO or is there any update for that? 

thanks

**Comment by FranklinZty** [comment]
I got the same question, when I use 2*2 mimo in two different frequency, neither ends can demodulate the correct signal.😩
Do you have the same situation，bro？
I hope someone can provide a solution.   🤔
