### ISSUE TITLE
Frequency Range?

### ISSUE THREAD

**Issue by 0xCoto** [cclabsInc/RFCrack#2]
What is the supported frequency range?

**Comment by cclabsInc** [comment]
Whatever the card you purchased supports..  If you are using the yardstick read the following: 
https://greatscottgadgets.com/yardstickone/

official operating frequencies: 300-348 MHz, 391-464 MHz, and 782-928 MHz
unofficial operating frequencies: 281-361 MHz, 378-481 MHz, and 749-962 MHz
