### ISSUE TITLE
Update Kali

### ISSUE THREAD

**Issue by kevtheskin** [cclabsInc/RFCrack#20]
Hello there.  Can someone tell me what this means please. Had to reinstall my Kali box and when I install rfcrack i get this error ImportError: No module named builtins  . Thanks for any info in advanced .

Cheers Kev

**Comment by chinemys** [comment]
try to watch rfcat installation, install latest version .with python 3 you have to use modified version rfcrack by mcdan in Pull Requests.
don't use Kali repository to update rfcat, use the one on github

**Comment by kevtheskin** [comment]
> try to watch rfcat installation, install latest version .with python 3 you have to use modified version rfcrack by mcdan in Pull Requests.
> don't use Kali repository to update rfcat, use the one on github

Hello there, Thanks for you reply. Can you please tell how do you download the new RFCrack.py . I am just an old new linux noobie. Thanks for your help.  73's Kev
