### ISSUE TITLE
RfCat is pip-installable for Py3. please update.

### ISSUE THREAD

**Issue by atlas0fd00m** [cclabsInc/RFCrack#21]
nice work so far!  i'm liking the direction this project is going (although admittedly i haven't had a chance to make use of it yet).

this is just a note that RfCat works with Py3 now, and is pip-installable.  check it out, give me any feedback you may have.  then you might want to update your INSTALL docs.

hack fun!
@

**Comment by atlas0fd00m** [comment]
oh, and you'll want to migrate the code to Py3.  let me know if you need anything.

**Comment by chinemys** [comment]
i would love to have bruteforce inside rfcrack so much, that would be great.
the only one able to do it for now is Pandwarf but it is not open source and the device is very expensive unfortunately.
cclabsInc come back to us please !!!

**Comment by cclabsInc** [comment]
Sounds good.. If this is indeed working with the official branch of Rfcat in python3 I will start updating this when I get back in the states next month and have a new version out..

**Comment by cclabsInc** [comment]
I just looked at RFCat it says that its still python 2.7

**Comment by atlas0fd00m** [comment]
if you're talking about the setup.py, it indicates >= 2.7.  we've attempted to keep in Py2-compatible.  let me know if you see anything that i should change, or if you think that's confusing.  we're heavily enough in the time of py3, i suppose it wouldn't kill me to update it.  i've tried to leave it supporting 2.7 for those who have a hard time getting off py2 on particular distros/setups.

**Comment by cclabsInc** [comment]
Oh ok cool, I misread it then... I will update this when I get back to the states in a few weeks and if it works I will start on new features.. I put a hold on new stuff with this project till a V3 version was ready..

**Comment by cclabsInc** [comment]
> i would love to have bruteforce inside rfcrack so much, that would be great.
> the only one able to do it for now is Pandwarf but it is not open source and the device is very expensive unfortunately.
> cclabsInc come back to us please !!!

Yep I will start updating this in a few weeks when I get back home and have hardware available to me.. Then assess what new features or fixes I will add.    Although regarding bruteforcing.. what specifically are you referring to?

**Comment by cclabsInc** [comment]
I believe I have updated everything to python3 in the code base as a step 1:  (mostly Fstrings and input)

Though I cannot test it as I am downloading an old version of Ubuntu I need to update rfcat on the device and noticed I cant do it with ubuntu 20 library versions so I have 18 downloading.. Hopefully I can confirm some basic functionality tomorrow on the newest release of ubuntu and newest version of python3 with this fan remote I have on my ceiling.

If that all works as intended I will take a look at cleaning up the code base beyond the F strings I added and input statements..  And also confirming pre-reqs on a clean ubuntu build and updating the install docs.
