### ISSUE TITLE
Feature request: support for RFQuack on EvilCrowRF

### ISSUE THREAD

**Issue by maichai** [cclabsInc/RFCrack#22]
I think the EvilCrowRF hardware is interesting as it allows for full duplex with two modems and the RFQuack firmware would be supportive for complex use cases as implemented in RFCrack.

EvilcrowRF: it is even much cheaper than YARDstick One.
https://github.com/joelsernamoreno/EvilCrow-RF

RFQuack:
https://github.com/rfquack/RFQuack

Are you still interested in such gadgets and use cases? It would be great to repace RFcat with RFquack in RFcrack.

**Comment by cclabsInc** [comment]
I dont plan on buying that hardware... this is for the yardstick..
