### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'map' and 'int'

### ISSUE THREAD

**Issue by bigoper** [cclabsInc/RFCrack#24]
**Thank you for sharing your experience & tools with us!**

# CONTEXT
- following your article [here](http://console-cowboys.blogspot.com/2018/01/hacking-everything-with-rf-and-software.html)
- executing the command `python RFCrack.py -n -g -u 1f0fffe0fffc01ff803ff007fe0fffc1fff83fff07ffe0007c`

# TESTING FUNCTIONALITY
- I was able to execute other commands. (ex. `python RFCrack.py -k -f 390000000`)

# ENV
- Python 3.9.7
- Mac OSX

**Comment by cclabsInc** [comment]
Ok, soooo in that error what line was that error for and what source file..

**Comment by cclabsInc** [comment]
Issue fixed... Found the line and updated the type
