### ISSUE TITLE
Cannot Jam

### ISSUE THREAD

**Issue by jammingbr** [cclabsInc/RFCrack#27]
Hi there, I am able to sniff and record signals with one Yardstick , but when I try to jam , I get the following error: 

> $ sudo python3 RFCrack.py -j -F 314980000
> Starting Jamming on: 314980000
> Traceback (most recent call last):
>   File "RFCrack.py", line 198, in <module>
>     jam.jamming(j, "start", rf_settings, args.rolling_code)
>   File "/home/jammboy/RFCrack/RFCrack/src/jam.py", line 27, in jamming
>     j.setModeTX() # start transmitting
>   File "/usr/local/lib/python3.8/dist-packages/rfcat-1.9.6-py3.8.egg/rflib/chipcon_nic.py", line 127, in setModeTX
>   File "/usr/local/lib/python3.8/dist-packages/rfcat-1.9.6-py3.8.egg/rflib/chipcon_nic.py", line 119, in setRfMode
>   File "/usr/local/lib/python3.8/dist-packages/rfcat-1.9.6-py3.8.egg/rflib/chipcon_usb.py", line 616, in send
>   File "/usr/local/lib/python3.8/dist-packages/rfcat-1.9.6-py3.8.egg/rflib/chipcon_usb.py", line 579, in recv
> rflib.chipcon_usb.ChipconUsbTimeoutException: Timeout waiting for USB response.
> ===== RESETUP set from recv thread

Do I need 2-nd Yardstick to be able to jam only? 
Also very frequent I get USB timeout errors. 

In the same time , if I use the following code from another source, I am able to jam : 
from rflib import * 

> d = RfCat()
> #d.setFreq(868500000)  #868
> d.setFreq(433800000)  #433.92
> #d.setFreq(315300000)  #315
> d.setMdmModulation(MOD_ASK_OOK)
> d.setMdmDRate(4800)
> #d.setMaxPower()
> print("Starting")
> while(1):
> 	d.RFxmit(b"\x84\xe7\x08\x42\x10\x84\xe7\x38\x00\x00\x00\x00\x00\x00"*10)

**Comment by slikkmulah** [comment]
were you ever able to fix this? I'm having same problem =(

**Comment by cclabsInc** [comment]
Yea so I am doing updates now looks like the Set Transmit function doesnt work properly...  Looking for a work around.. I havn't used this till now on python3.. So just did a bunch of updates.. but now looking into this..

**Comment by cclabsInc** [comment]
OK pretty sure I just fixed this.. different method..
