### ISSUE TITLE
hanging?

### ISSUE THREAD

**Issue by sigmamale1980** [cclabsInc/RFCrack#3]
Hi, first off, thank you for this excellent script.
I kinda noticed that everytime i start using rfcrack my yardstick's green light refuses to switch off
therefore unable to access the device the second time & the only solution is to unplug'n'replug the stick
again?! 

can't figure out whether its an issue with my os or rfcrack? but rfcat works just fine.
i'm running Debian testing.

Thx in adv.

**Comment by cclabsInc** [comment]
Yea thats just how the yardstick is with RFcat, if you have to ctrl-C / ctrl-Z anything at all it will break and you have to unplug it.  Drove me nuts before I wrote this RFcrack which mostly fails gracefully 

Tips
If you hit enter on scanning features it will close gracefully same for Jamming
On one off stuff wait for the process to finish so it closes gracefully
Don't use CTRL Z or C the yardstick with RFcat doesn't like that..

**Comment by sigmamale1980** [comment]
Thanks & appreciate the reply, at least it works.. great script.
