### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by mrc333777** [cclabsInc/RFCrack#31]
can you fix your logo?

![cc](https://github.com/user-attachments/assets/f23e692e-682f-4a5c-a3a1-7e8c6b9b2535)

**Comment by cclabsInc** [comment]
Fix it to what?   I don't see an issue with it..

**Comment by cclabsInc** [comment]
Oh gotcha.. in the ReadMe.... Done

**Comment by mrc333777** [comment]
did you see the photo? oh its fixed now
    On Sunday, December 8, 2024 at 05:10:52 PM EST, Ficti0n ***@***.***> wrote:  
 
 


Fix it to what? I don't see an issue with it..

**Comment by cclabsInc** [comment]
Yep should be all good.. Good catch.. updated a ton of stuff today

**Comment by mrc333777** [comment]
thank you for that

    On Sunday, December 8, 2024 at 07:07:41 PM EST, Ficti0n ***@***.***> wrote:  
 
 


Yep should be all good.. Good catch.. updated a ton of stuff today
