### ISSUE TITLE
HackRF One compatibility

### ISSUE THREAD

**Issue by raffaeler** [cclabsInc/RFCrack#5]
Any chance to support the HackRF One device?
BTW congrats for the great work

**Comment by cclabsInc** [comment]
HackRF does not support RFCat libraries..

**Comment by cclabsInc** [comment]
HackRF does not support RFCat libraries, RFcat interfaces with the C1111 hardware which is used in RFcrack.. They are completely different pieces of hardware and methodology for usage.. I have a HackRF but rarely use it as the yardstick is much more extendable.
RFCrack also isn't an open source community tool, just my personal test bench.. So basically will only support my own testing workflows. I may script HackRF it at some point.. but not in RFCrack
